# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - CSharpBlazorCICDSkeleton

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9a2f84ad49e04625adbbb1d64bdb74a2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d44aed12b4554a96aee0648c3bc60ec9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_9a2f84ad49e04625adbbb1d64bdb74a2 }}/csharpblazorcicdskeleton:${{ github.sha }}
        file: ./CSharpBlazorCICDSkeleton.Frontend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CSharpBlazorCICDSkeleton'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_577ebdda574c47e594b116527f6e3258 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_9a2f84ad49e04625adbbb1d64bdb74a2 }}/csharpblazorcicdskeleton:${{ github.sha }}'
